Update README.md
FriendsOfREDAXO/yform_spam_protection pull request #44
Opened 2021-07-16 19:57 UTC by thorol

Tipp ergänzt mit Hinweis auf doppelte Absendung des Formulars.

2021-07-16 20:50 UTC, alxndr-w requested changes
Danke für die Vorarbeit @thorol. Du kannst meine Korrektur direkt übernehmen, dann kann sie jemand von FOR in den Code aufnehmen.

2021-07-16 20:50 UTC, alxndr-w commented on README.md
> +Sollte trotz aller beachteten Timings und obigem Tipp zu mehreren Formularen beim Versenden der Fehler 'session-microtime nicht eingehalten...' (bei eingeschalteten Debug-Modus) dauerhaft kommen, so
```suggestion
Sollte trotz aller beachteten Timings und obigem Tipp zu mehreren Formularen beim Versenden der Fehler „session-microtime nicht eingehalten...“ (bei eingeschalteten Debug-Modus) dauerhaft kommen, so ist zu prüfen, ob das Formular evtl. nicht zweimal abgesendet wird. 

Mögliche Ursache dafür ist, dass im Template beispielsweise `REX_ARTICLE[]` oder `$this->getArticle()` mehr als einmal verwendet werden.
```

2021-07-19 14:03 UTC, alxndr-w commented
Von meiner Seite aus passt es. Jetzt muss es noch jemand von FOR mergen.

2021-08-13 15:13 UTC, alxndr-w commented
@marcohanke ? @TobiasKrais evtl. ?

2021-08-13 18:48 UTC, merged

2021-08-13 18:49 UTC, TobiasKrais commented
Ohne es anzuschauen merge ich das mal. Wenn du, Alex das abgesegnet hast, dann passt das für mich ;-)