IP Whitelist and ignore logged-in users features added
FriendsOfREDAXO/yform_spam_protection pull request #46
Opened 2021-08-16 13:32 UTC by omphteliba

Wie in https://github.com/FriendsOfREDAXO/yform_spam_protection/issues/45 angeregt: es kann einen IP Whitelist geführt werden und es kann aktiviert werden, dass ein eingeloggter Redaxo Benutzer ignoriert wird.

2021-08-17 07:19 UTC, alxndr-w commented on lang/de_de.lang
> +yform_spam_protection_ip_whitelist_notice = Liste von IPs die nicht blockiert werden sollen. IPs mit Komma trennen.
```suggestion
yform_spam_protection_ip_whitelist_notice = Liste von IPs, die nicht blockiert werden sollen. Z.B. <code>192.168.0.1,192.168.0.2,192.168.0.3</code>
```

2021-08-17 07:20 UTC, alxndr-w commented on lang/de_de.lang
> +yform_spam_protection_ignore_user = Eingeloggt Benutzer ignorieren
```suggestion
yform_spam_protection_ignore_user = Eingeloggte Backend-Benutzer ignorieren
```

2021-08-17 07:21 UTC, alxndr-w commented on lang/en_gb.lang
> +yform_spam_protection_ip_whitelist_notice = List of IPs that should not be blocked. Separate IPs with comma.
```suggestion
yform_spam_protection_ip_whitelist_notice = List of IPs that should not be blocked, e.g.: <code>192.168.0.1,192.168.0.2,192.168.0.3</code>
```

2021-08-17 07:21 UTC, alxndr-w commented on lang/de_de.lang
> +yform_spam_protection_ignore_user_notice = Ignoriert Benutzer die im Redaxo Backend eingeloggt sind.
```suggestion
yform_spam_protection_ignore_user_notice = Ignoriert Benutzer, die im REDAXO-Backend eingeloggt sind.
```

2021-08-17 07:21 UTC, alxndr-w commented on lang/en_gb.lang
> +yform_spam_protection_ignore_user_notice = Ignores users who are logged into the Redaxo backend.
```suggestion
yform_spam_protection_ignore_user_notice = Ignores users who are logged into the REDAXO backend.
```

2021-08-17 07:22 UTC, alxndr-w requested changes
Lektorat

2021-08-17 07:24 UTC, alxndr-w commented
Ist der Code gut getestet, mal alle Szenarien durchprobiert? Das wären imho:

- [ ] Eine IP gewhitelistet, nicht eingeloggt, Regel für REDAXO-Backendnutzer aktiv
- [ ] Mehrere IPs gewhitelistet, nicht eingeloggt, Regel für REDAXO-Backendnutzer aktiv
- [ ] Eine IP gewhitelistet, eingeloggt, Regel für REDAXO-Backendnutzer aktiv
- [ ] Mehrere IPs gewhitelistet, eingeloggt, Regel für REDAXO-Backendnutzer aktiv
- [ ] Eine IP gewhitelistet, nicht eingeloggt, Regel für REDAXO-Backendnutzer inaktiv
- [ ] Mehrere IPs gewhitelistet, nicht eingeloggt, Regel für REDAXO-Backendnutzer inaktiv
- [ ] Eine IP gewhitelistet, eingeloggt, Regel für REDAXO-Backendnutzer inaktiv
- [ ] Mehrere IPs gewhitelistet, eingeloggt, Regel für REDAXO-Backendnutzer inaktiv

2021-08-19 07:26 UTC, merged

2021-08-19 14:42 UTC, alxndr-w commented
@omphteliba du hast meine Änderungsvorschläge in den lang-Dateien übersehen, oder?

2021-08-19 15:07 UTC, omphteliba commented
@alxndr-w nein, die habe ich gesehen, ich dachte die werden durch den Merge übernommen.

2021-08-19 15:08 UTC, alxndr-w commented
Ne, das waren Vorschläge, die hätten von dir quasi noch bestätigt werden müssen durch einen Klick.